### PR TITLE
File upload fixes for Android and Windows

### LINKED ISSUE #117: Buggy implementation of file upload boundaries on Android
The boundaries for `multipart/form-data` file upload request are not generated correctly on Android.

First, it writes two `crlf` sequences before the ending boundary, first here:

https://github.com/birdofpreyru/react-native-fs/blob/604d8a1c27642b5ab2adb58ebb8687c7130cf8f2/android/src/main/java/com/drpogodin/reactnativefs/Uploader.kt#L134

And later here where it is part of the `tail` string:

https://github.com/birdofpreyru/react-native-fs/blob/604d8a1c27642b5ab2adb58ebb8687c7130cf8f2/android/src/main/java/com/drpogodin/reactnativefs/Uploader.kt#L140

Second, the boundary string itself is not unique, which might cause random issues if the uploaded data contains the same string:

https://github.com/birdofpreyru/react-native-fs/blob/604d8a1c27642b5ab2adb58ebb8687c7130cf8f2/android/src/main/java/com/drpogodin/reactnativefs/Uploader.kt#L45C13-L45C21

Here's how the boundary is generated on iOS:
https://github.com/birdofpreyru/react-native-fs/blob/604d8a1c27642b5ab2adb58ebb8687c7130cf8f2/ios/Uploader.mm#L120

Note that this is a long-standing issue and I'm willing to submit a PR to fix it.

### PR DESCRIPTION
**Pull request by tero-paananen**
Fixes #117 #118

- Removes extra marks `crlf` from file upload multipart request on Android and uses better boundary. Request length calculation fixes.
- Fixes issue where upload file's `fields` parameter values were sent into request headers on Windows. Better multipart boundary. Remove some error catching in code. It is better to send errors to caller.
- Fixes example app to build and start on all platforms iOS, Android and Windows.
- Android can read filetype now from example file öäü-upload-file-2.txt

Known issues

- Example on iOS builds but does not start because some issues with local react-native-static-server. Thats why example does not use fields because i currently did not manage to run example. react-native-fs file upload with fields parameters works and is tested in our iOS application. See more below.

### CODE REVIEW

**Comment by tero-paananen** [comment]
iOS Simulator testing

- I updated `example/package.json` ` "ios": "react-native run-ios --simulator 'iPad Air (5th generation)'",` 
- Called `pod install` 
- Called `RN_STATIC_SERVER_WEBDAV=1 yarn example ios` 


`uploadFiles` shows error in example app but method work when using rn-fs module from our app.

 
Simulator Screenshot - iPad Air (5th generation) - 2025-08-11 at 09 59 06

File: example/src/methods/upload.ts [hunk 1]
```diff
@@ -10,15 +10,18 @@ import type { TestMethods } from '../TestTypes';
 import { notPlatform, Result, tryUnlink } from '../TestUtils';
 import { CONTENT, PATH } from '../TestValues';
 
-const UPLOAD_FILES_CONTROL_ANDROID = `--*****
+const UPLOAD_FILES_CONTROL_ANDROID = `boundary
+Content-Disposition: form-data; name="a"
+
+b
```
Comment (birdofpreyru) [inline example/src/methods/upload.ts:16]: @tero-paananen is this `b` a misprint, should this line be removed?

File: example/src/methods/upload.ts [hunk 2]
```diff
@@ -29,12 +32,19 @@ GÖÖÐ
 
 `;
 
-const UPLOAD_FILES_CONTROL_WINDOWS = `-------
+const UPLOAD_FILES_CONTROL_WINDOWS = `boundary
+Content-Length: 1
+Content-Type: text/plain; charset=UTF-8
+Content-Disposition: form-data; name="a"
+
+b
```
Comment (birdofpreyru) [inline example/src/methods/upload.ts:40]: ...or is it an intentional part of the test? :thinking:

File: example/src/methods/upload.ts [hunk 3]
```diff
@@ -62,10 +72,19 @@ export const uploadTests: TestMethods = {
 
       await tryUnlink(targetDevicePath);
 
+      const fields = Platform.select({
+        ios: undefined,
+        macos: undefined,
+        default: {
+          a: 'b',
```
Comment (birdofpreyru) [inline example/src/methods/upload.ts:79]: ok, I'd say let's change `"b"` to something less confusing, say `"mock value"`?

**Review by birdofpreyru — COMMENTED** [review]
Ok, overall it looks fine for me to merge. I don't know how exactly those boundaries should be formatted, and not much interested to double-check related specifications; so I just rely on you knowing what you are doing, and that you did not mess it up.

> Example on iOS builds but does not start because some issues with local react-native-static-server. Thats why example does not use fields because i currently did not manage to run example.

Yeap, the static server is also sensitive to the exact RN version... that's why, to avoid extra headache, I just keep it all working with the latest RN; thus temporarily not caring about Windows due to them lagging behind latest RN.
